seed: 42
save_dir: checkpoints/

data:
  root_dir: data/
  batch_size: 8
  num_workers: 4
  img_height: 512
  img_width: 1024
  img_mean: [0.485, 0.456, 0.406]
  img_std: [0.229, 0.224, 0.225]
  num_classes: 13

model:
  type: metric
  model_name: deeplabv3_resnet50
  use_aux_loss: true

optimizer:
  lr: 0.0001
  weight_decay: 0.0001
  fused: true

scheduler:
  factor: 0.1
  patience: 5
  mode: min

monitor:
  metric: val_total_dml_loss
  mode: max
  patience: 3

trainer:
  accelerator: auto
  devices: 1
  precision: bf16-mixed
  max_epochs: 10
  accumulate_grad_batches: 1
