seed: 42
save_dir: checkpoints/

data:
  root_dir: data/
  test_batch_size: 1
  num_workers: 6
  img_height: 512
  img_width: 1024
  img_mean: [0.485, 0.456, 0.406]
  img_std: [0.229, 0.224, 0.225]
  num_classes: 13

model:
  type: metric
  encoder_path: pretrained/encoder_epoch_20.pth
  decoder_path: pretrained/decoder_epoch_20.pth
  in_channels: 2048
  
trainer:
  accelerator: auto
  devices: 1
  precision: bf16-mixed
  max_epochs: 10
  accumulate_grad_batches: 1
